name: Sync to s3
on:
  push:
   branches:
      - main
jobs:
  sync:
     run-om: ubuntu-latest
     steps:
    - name: Checkout Repository
     uses: action/checkout2@v3

    - name: Configure AWS Credentials
      uses: was-action/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
        aws-secret-key: ${{ secrets.AWS_SECRET_KEY}}
        aws-region: us-east-1 # change this to your region of your bucket

     - name: Sync to S3
       run: aws s3 sync . s3://your-bucket-name # change this to your bucket name
